name: 'ris-adm-literature-backend-container'
services:
  postgres:
    container_name: 'ris-adm-literature-postgres'
    image: 'postgres:14-alpine'
    environment:
      - 'POSTGRES_DB=ris_adm_literature'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    command: ["postgres", "-c", "max_connections=150"]
    ports:
      - '5432:5432'
    volumes:
      - ./docker-initialization:/docker-entrypoint-initdb.d/

  keycloak:
    container_name: 'ris-adm-literature-keycloak'
    image: 'quay.io/keycloak/keycloak:26.2.5'
    environment:
      - 'KEYCLOAK_ADMIN=admin'
      - 'KEYCLOAK_ADMIN_PASSWORD=admin'
    ports:
      - '8443:8080'

    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    command: ["start-dev", "--import-realm"]


