spring:
  application.name: ris-adm-literature-backend
  jpa:
    # Run Hibernate DDL BEFORE data.sql
    defer-datasource-initialization: true
    # Disable Hibernate's automatic table creation.
    hibernate:
      ddl-auto: none

  datasource:
    adm:
      url: jdbc:postgresql://${database.host:localhost}:${database.port:5432}/${database.database:ris_adm_literature}?currentSchema=${adm.database.schema:adm}
      username: ${adm.database.user:adm}
      password: ${adm.database.password:adm}
      driver-class-name: org.postgresql.Driver
    literature:
      url: jdbc:postgresql://${database.host:localhost}:${database.port:5432}/${database.database:ris_adm_literature}?currentSchema=${literature.database.schema:literature}
      username: ${literature.database.user:literature}
      password: ${literature.database.password:literature}
      driver-class-name: org.postgresql.Driver
    references:
      url: jdbc:postgresql://${database.host:localhost}:${database.port:5432}/${database.database:ris_adm_literature}?currentSchema=${references.database.schema:references_schema}
      username: ${references.database.user:references_schema}
      password: ${references.database.password:references_schema}
      driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${oauth2.issuer-uri:http://localhost:8443/realms/ris}

management:
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  swagger-ui:
    path: /api/swagger-ui
  api-docs:
    path: /api/swagger-ui/v3/api-docs

# Every hour between 8:00 and 18:00 every day between Monday and Friday
cronjob.DocumentationUnitIndexJob: "0 0 8-18 * * Mon-Fri"

frontend:
  auth:
    url: ${oauth2.frontend-url:http://localhost:8443}
    realm: ${oauth2.realm:ris}
    clientId: ${oauth2.client-id:ris-adm-literature-local}

local:
  file-storage: output/s3-mock-storage

s3:
  bucket:
    adm:
      public:
        access-key: ${s3.adm.public.access-key:test}
        access-key-id: ${s3.adm.public.access-key-id:test}
        bucket-name-ref: ${s3.bucket.adm.public.bucket-name:local-mock-bucket-adm}
    literature:
      public:
        access-key: ${s3.literature.public.access-key:test}
        access-key-id: ${s3.literature.public.access-key-id:test}
        bucket-name-ref: ${s3.bucket.literature.public.bucket-name:local-mock-bucket.literature}
