on:
  workflow_call:
    secrets:
      RIS_REPORTS_DEPLOY_PRIVATE_KEY:
        required: true

jobs:
  compile-and-push-e2e-HTML-report:
    continue-on-error:
      true
    runs-on: ubuntu-latest
    env:
      reports-repo: digitalservicebund/ris-reports
    steps:

      ###############################
      # Compile e2e reports (from their various workflows)
      ###############################
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-frontend

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v7
        with:
          path: tmp/e2e-test-report
          pattern: frontend-e2e-test-report.blob*
          merge-multiple: true

      # end of downloads, create single report
      - name: Generate HTML report out of all the blobs
        working-directory: ./frontend
        run: |
          pnpx playwright merge-reports --reporter html ../tmp/e2e-test-report
      - name: Upload e2e HTML test report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: frontend-e2e-test-report-html
          retention-days: 3
          path: frontend/playwright-report

      ########################################################################
      # Downloading and adding test reports
      # Note: actually pushing the reports is a separate step after all these
      ########################################################################


      # This special step needs to happen before any "add-ris-report" action
      # (otherwise the folder is not git repository and does not support git commands)
      - name: Checkout ris-reports
        uses: actions/checkout@v6
        with:
          repository: ${{ env.reports-repo }}
          ssh-key: ${{ secrets.RIS_REPORTS_DEPLOY_PRIVATE_KEY }}
          path: ris-reports


      - name: Download artifact frontend e2e test report
        uses: actions/download-artifact@v7
        with:
          name: frontend-e2e-test-report-html
          path: ris-reports/tmp/frontend-e2e-test-report-html
      - name: Add frontend e2e test report for push
        uses: digitalservicebund/add-ris-report@c6c8735d23295c36a271c75e7dedc9b6b9a9ef5e
        with:
          filePath: ris-reports/tmp/frontend-e2e-test-report-html
          destinationDir: ris-reports/test-reports/ris-adm-literature/frontend/e2e-tests
          reportIsDirectory: true

      ##############################################
      # Finally: pushing the reports to ris-reports
      ##############################################
      - name: Setup git config
        working-directory: ris-reports
        run: |
          git config user.name "${{ github.repository }}"
          # This email identifies the commit as GitHub Actions - see https://github.com/orgs/community/discussions/26560
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name:
          Push reports
          # we use `toJSON(...)` below to escape double quotation marks
        working-directory: ris-reports
        run: |
          git diff-index --cached --quiet HEAD ||
            git commit \
              -m ${{ toJSON(github.event.head_commit.message) }} \
              -m "From commit: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}" &&
            git push origin main &&
            echo "Pushed reports to ${{ github.server_url }}/${{ env.reports-repo }}" >> $GITHUB_STEP_SUMMARY
